name: ecofriendly
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.7.0 <4.0.0'  # ✅ Corrección agregada aquí

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.0
  image_picker: ^0.8.6
  font_awesome_flutter: ^10.0.0
  cupertino_icons: ^1.0.8
  url_launcher: ^6.1.10
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/